version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: 'mongodb-container'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=secret
      - MONGO_INITDB_DATABASE=bup-appointment
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo-js:ro
      - ./mongo-volume:/data/db
    ports:
      - '27017:27017'
  #bup:
   # image: com.appointment.services/bup:0.0.1-SNAPSHOT
    #ports:
     # - 8081:8080
    #depends_on:
     # - databese
